# Generated by Django 4.2.3 on 2023-07-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
    ]
