# Generated by Django 4.2.3 on 2023-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_alter_comentarios_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='modificado',
            field=models.DateTimeField(verbose_name='modificado'),
        ),
    ]
