# Generated by Django 4.2.3 on 2023-07-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='contactos',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
