# Generated by Django 4.2.3 on 2023-07-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_rename_nombre_contactos_nombre_contactos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='asunto',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='email',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.TextField(max_length=80),
        ),
    ]
