# Generated by Django 4.2.3 on 2023-07-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_alter_contactos_asunto_alter_contactos_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='asunto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
